### ISSUE TITLE
Requesting new release

### ISSUE THREAD

**Issue by urlicht** [fundamental/TotalVariation.jl#3]
Could you make a new release with the updated changes? (mainly Julia 1.0 compatibility)
Thanks!

**Comment by fundamental** [comment]
On 06-10, Jungsoo Kim wrote:
> Could you make a new release with the updated changes? (mainly Julia 1.0 compatibility)
> Thanks!

Thanks for the reminder.
I should be able to address this later this week.

**Comment by fundamental** [comment]
Closed via https://github.com/JuliaRegistries/General/pull/2166
